# Fonts

font_family 	monaco
font_size 	12.0

# Theme
foreground 	#FFFFFF
background	#181d26

# Black
color0 #2d3646
color8 #455368

# Red
color1 #c8233b
color9 #ed3855

# Green
color2  #7bbcb2
color10 #badad5

# Yellow
color3  #63839c
color11 #9ab2c6

# Blue
color4  #609bb8
color12 #a3c4d5

# Magenta 
color5  #609bb8
color13 #a3c4d5

# Cyan
color6  #7bbcb2
color14 #badad5

# White
color7  #feffff
color15 #feffff


#macos_hide_titlebar true
window_padding_width 10
