#!/bin/bash

NOCOLOR='\033[0m'
LIGHTCYAN='\033[1;36m'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for file in $DIR/enabled/*; do
	source $file
done

echo -e "[ ${LIGHTCYAN}Running $SHELL with profiles loaded ${NOCOLOR}]"
